const mongoose = require('mongoose');

const NoteSchema = new mongoose.Schema({
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    // The note content is double-encrypted (E2EE by frontend + SSE by backend)
    // We store it as a string (base64 or hex)
    encryptedContent: {
        type: String,
        required: true
    },
    // The Initialization Vector used by the BACKEND encryption (SSE)
    // We store it as a hex string
    iv: {
        type: String,
        required: true
    },
    // The Authentication Tag generated by AES-GCM on the BACKEND
    // Ensures the ciphertext has not been tampered with
    authTag: {
        type: String,
        required: true
    }
}, { timestamps: true });

// Note: The frontend's IV and AuthTag (for the E2EE layer) are encapsulated
// within the `encryptedContent` before it reaches the backend, or they can be
// passed and stored separately. For this implementation, we assume the frontend
// payload includes its own IV/AuthTag concatenated or JSON stringified, which 
// is then entirely encrypted by the backend.

module.exports = mongoose.model('Note', NoteSchema);
